/**
Given a list of cities, implement an input box that shows a dropdown of cities that match the inputted text.

On click of a city, it should replace the input box text and hide the dropdown.

const cities = ['Boston', 'Berlin', 'Los Angeles', 'San Francisco', 'Santa Clara'];
*/

let cities = [];

// Dropdown Element
let $dropdown = document.getElementById('dropdown-list'),
    $input = document.getElementById('cities-list');

dropdownList = () => {
  // Search Value
  let $citiesInput = document.getElementById('cities-list').value.toLowerCase(),
  // Stores value length
      $citiesInputLength = $citiesInput.length,
  // Stores filtered cities list
      list = [];

  // Clears dropdown list
  while ($dropdown.firstChild) {
    $dropdown.removeChild($dropdown.firstChild);
  }

  // Only filters if something is inputted
  if ( $citiesInputLength ) {

    // Filters cities into list
    cities.forEach((val, i, e) => {
      let result = (val.substr(0,$citiesInputLength)).toLowerCase();
      if ( result == $citiesInput ) {
        list.push(val);
      }
    });

    // Builds dropdown with list data
    list.forEach(city => {
      let item = '<div onclick="setCity(this)" style="cursor:pointer;">' + city + '</div>';
      $dropdown.innerHTML += item;
    });
  }
}

// Sets city inside of input
setCity = (city) => {
  $input.value = city.innerHTML;
  $dropdown.innerHTML = '';
}

// Cities data bank
const data = [{"cities":"Kudowa-Zdrój"},
{"cities":"Sheli"},
{"cities":"Beidajie"},
{"cities":"Steinsel"},
{"cities":"Tiksi"},
{"cities":"Dumalneg"},
{"cities":"San Antonio"},
{"cities":"Staryy Merchyk"},
{"cities":"Samashki"},
{"cities":"Jielong"},
{"cities":"Contagem"},
{"cities":"Uthai Thani"},
{"cities":"Kangani"},
{"cities":"Fontinha"},
{"cities":"Alfortville"},
{"cities":"Linjiang"},
{"cities":"Lancaster"},
{"cities":"Pedra"},
{"cities":"Zorak"},
{"cities":"Kwali"},
{"cities":"Budapest"},
{"cities":"Arras"},
{"cities":"Unquillo"},
{"cities":"Semikarakorsk"},
{"cities":"Pestovo"},
{"cities":"Żarnów"},
{"cities":"Souto da Costa"},
{"cities":"Sang-e Māshah"},
{"cities":"Bukama"},
{"cities":"Rosario de Mora"},
{"cities":"Bakulong"},
{"cities":"Airuk"},
{"cities":"María la Baja"},
{"cities":"Neepawa"},
{"cities":"Corpus"},
{"cities":"Ōdachō-ōda"},
{"cities":"Oslo"},
{"cities":"Tabalong"},
{"cities":"Langchi"},
{"cities":"Llano de Piedra"},
{"cities":"Putrajaya"},
{"cities":"Vukovar"},
{"cities":"Dainan"},
{"cities":"Vanimo"},
{"cities":"Nantes"},
{"cities":"Hinapalanan"},
{"cities":"Córdoba"},
{"cities":"Quintães"},
{"cities":"Riangderi"},
{"cities":"Arrifes"},
{"cities":"Tam Kỳ"},
{"cities":"Suslonger"},
{"cities":"Shangani"},
{"cities":"Ibaraki"},
{"cities":"Xiachengzi"},
{"cities":"Dhalie"},
{"cities":"Douz"},
{"cities":"Oral"},
{"cities":"Lubin"},
{"cities":"Gémeos"},
{"cities":"Rinconada"},
{"cities":"Zaniemyśl"},
{"cities":"Montfavet"},
{"cities":"La Celia"},
{"cities":"Gorodishche"},
{"cities":"Ibiporã"},
{"cities":"Bicesse"},
{"cities":"Sindang"},
{"cities":"Juarez"},
{"cities":"Outeiro"},
{"cities":"Togur"},
{"cities":"Libiąż"},
{"cities":"Sampit"},
{"cities":"Puerto Plata"},
{"cities":"Carmen"},
{"cities":"Alistráti"},
{"cities":"Urayasu"},
{"cities":"Mae Hi"},
{"cities":"Nubl"},
{"cities":"Kornyn"},
{"cities":"Pointe-à-Pitre"},
{"cities":"Medvezh’yegorsk"},
{"cities":"Jieshi"},
{"cities":"Ushibuka"},
{"cities":"Zherdevka"},
{"cities":"Jaba‘"},
{"cities":"Olyshivka"},
{"cities":"Chicago"},
{"cities":"Maiwang"},
{"cities":"Zaporizhzhya"},
{"cities":"Cañada de Gómez"},
{"cities":"Chimtāl"},
{"cities":"Palermo"},
{"cities":"Ranilug"},
{"cities":"Manolás"},
{"cities":"Tongkiling"},
{"cities":"Shuibatang"},
{"cities":"Peishe"},
{"cities":"Venda"},
{"cities":"Yavne"},
{"cities":"San Isidro"},
{"cities":"Gualeguaychú"},
{"cities":"Dungang"},
{"cities":"Breves"},
{"cities":"Karasuyama"},
{"cities":"Jakubów"},
{"cities":"Xiongbei"},
{"cities":"Pavino"},
{"cities":"Laixi"},
{"cities":"Bahía de Caráquez"},
{"cities":"Gendiwu"},
{"cities":"San Vicente"},
{"cities":"Igunga"},
{"cities":"Shinjō"},
{"cities":"Tinabogan"},
{"cities":"West Jerusalem"},
{"cities":"Betaf"},
{"cities":"Castelo"},
{"cities":"Forbach"},
{"cities":"København"},
{"cities":"San Jose del Monte"},
{"cities":"Monte Novo"},
{"cities":"Tonantins"},
{"cities":"Villeneuve-d'Ascq"},
{"cities":"Juexi"},
{"cities":"Yunfu"},
{"cities":"Antas"},
{"cities":"Jataí"},
{"cities":"Curuzú Cuatiá"},
{"cities":"Al Bawīţī"},
{"cities":"Kuantian"},
{"cities":"Tsaghkaber"},
{"cities":"Xiaheqing"},
{"cities":"Qorao’zak"},
{"cities":"Vrbno pod Pradědem"},
{"cities":"Sidoger Lebak"},
{"cities":"Opočno"},
{"cities":"Bakungan"},
{"cities":"Jiangwang"},
{"cities":"Khakhea"},
{"cities":"Solna"},
{"cities":"Oslo"},
{"cities":"Všemina"},
{"cities":"Kertabumi"},
{"cities":"Abreus"},
{"cities":"Matadi"},
{"cities":"Bielawy"},
{"cities":"Farmington"},
{"cities":"Bang Rakam"},
{"cities":"Krajan"},
{"cities":"Jiantiao"},
{"cities":"Nevel’sk"},
{"cities":"Na Tan"},
{"cities":"Sison"},
{"cities":"Siruma"},
{"cities":"Nanjing"},
{"cities":"Kobleve"},
{"cities":"Guansheng"},
{"cities":"Barrosa"},
{"cities":"Montceau-les-Mines"},
{"cities":"Bugene"},
{"cities":"Nambak Tengah"},
{"cities":"Carrasqueira"},
{"cities":"Darya Boyi"},
{"cities":"Beima"},
{"cities":"Jindong"},
{"cities":"Redondos"},
{"cities":"Vimmerby"},
{"cities":"Kitapak"},
{"cities":"Pasirdalem"},
{"cities":"Zicheng"},
{"cities":"Nevinnomyssk"},
{"cities":"Nunbaundelha"},
{"cities":"Pirallahı"},
{"cities":"Hospitalet De Llobregat, L'"},
{"cities":"Song’ao"},
{"cities":"Zhendong"},
{"cities":"Dolní Dunajovice"},
{"cities":"Xinglongquan"},
{"cities":"Al Fūlah"},
{"cities":"Newmarket on Fergus"},
{"cities":"Qusar"},
{"cities":"Tit Mellil"},
{"cities":"Peteranec"},
{"cities":"San Jose Village"},
{"cities":"Salas"},
{"cities":"Ogōri-shimogō"},
{"cities":"Whitchurch"},
{"cities":"Nepomuceno"},
{"cities":"Milove"},
{"cities":"Priiskovyy"},
{"cities":"Sagana"},
{"cities":"Jingxi"},
{"cities":"Fairview"},
{"cities":"Grande Prairie"},
{"cities":"Beihe"},
{"cities":"Vargas"},
{"cities":"Stockholm"},
{"cities":"Retenggoma"},
{"cities":"Gradec"},
{"cities":"Karafao"},
{"cities":"Longhua"},
{"cities":"Khuan Don"},
{"cities":"Bang Rak"},
{"cities":"Göteborg"},
{"cities":"Pristen’"},
{"cities":"Tempe"},
{"cities":"Longjiang"},
{"cities":"Binulasan"},
{"cities":"Canguaretama"},
{"cities":"Hebu"},
{"cities":"Roissy Charles-de-Gaulle"},
{"cities":"Wiśniewo"},
{"cities":"Colonia Elisa"},
{"cities":"Annan"},
{"cities":"Shuakhevi"},
{"cities":"Gainesville"},
{"cities":"Nanao"},
{"cities":"Kushar"},
{"cities":"Jājarm"},
{"cities":"Senhor da Serra"},
{"cities":"Belle-Anse"},
{"cities":"El Cobre"},
{"cities":"Poncokusumo"},
{"cities":"Dawuhan"},
{"cities":"Budva"},
{"cities":"Dār Kulayb"},
{"cities":"Zhongzhai"},
{"cities":"Pikalëvo"},
{"cities":"Al Qurayshīyah"},
{"cities":"Yemva"},
{"cities":"Velizh"},
{"cities":"Pedamaran"},
{"cities":"Planaltina"},
{"cities":"Sukomulyo"},
{"cities":"Dengfang"},
{"cities":"Pandak"},
{"cities":"Svorónos"},
{"cities":"Jasaan"},
{"cities":"Kansas City"},
{"cities":"Ulashan"},
{"cities":"Andilamena"},
{"cities":"Gombangan"},
{"cities":"Lubukalung"},
{"cities":"Petaling Jaya"},
{"cities":"Youkaichi"},
{"cities":"Timon"},
{"cities":"Nashville"},
{"cities":"Hantara"},
{"cities":"São Mateus"},
{"cities":"Vairão"},
{"cities":"Liushikou"},
{"cities":"Stockholm"},
{"cities":"Sri Jayewardenepura Kotte"},
{"cities":"Hedong"},
{"cities":"Binalbagan"},
{"cities":"Klatakan"},
{"cities":"Bassar"},
{"cities":"La Virtud"},
{"cities":"Sępólno Krajeńskie"},
{"cities":"Baojia"},
{"cities":"Pacucha"},
{"cities":"Novotroitsk"},
{"cities":"Nariño"},
{"cities":"Jeonju"},
{"cities":"Tonota"},
{"cities":"Frutal"},
{"cities":"Kruševac"},
{"cities":"Babakanloa"},
{"cities":"Ribeirinha"},
{"cities":"Bang Mun Nak"},
{"cities":"Magadan"},
{"cities":"Qionghai"},
{"cities":"Goubangzi"},
{"cities":"Raminho"},
{"cities":"Xuefeng"},
{"cities":"Dorogobuzh"},
{"cities":"Yanglin"},
{"cities":"Ängelholm"},
{"cities":"Santa Quitéria do Maranhão"},
{"cities":"Tempaling"},
{"cities":"Youkaichi"},
{"cities":"Kolobovo"},
{"cities":"Mobile"},
{"cities":"Monte de Fralães"},
{"cities":"Vagonoremont"},
{"cities":"Kiruna"},
{"cities":"Berëza"},
{"cities":"Campurrejo"},
{"cities":"Sindangbarang"},
{"cities":"Karinë"},
{"cities":"Doro Oo"},
{"cities":"Thatèng"},
{"cities":"Gaofeng"},
{"cities":"Khamis Mushait"},
{"cities":"Hwawŏn"},
{"cities":"5 de Mayo"},
{"cities":"Añelo"},
{"cities":"Kallinge"},
{"cities":"Santo Antônio de Posse"},
{"cities":"Poitiers"},
{"cities":"Kuncen"},
{"cities":"Daja"},
{"cities":"Pankshin"},
{"cities":"Padova"},
{"cities":"Lete"},
{"cities":"Xianghu"},
{"cities":"Yuezhao"},
{"cities":"Vynohradivka"},
{"cities":"Netanya"},
{"cities":"Sriwing"},
{"cities":"Palagao Norte"},
{"cities":"Cuntan"},
{"cities":"Qiaotou"},
{"cities":"Buenavista"},
{"cities":"Ilihan"},
{"cities":"Karangpapak"},
{"cities":"Jesenice"},
{"cities":"Stenungsund"},
{"cities":"Érd"},
{"cities":"Reforma"},
{"cities":"Vuokatti"},
{"cities":"Fulu"},
{"cities":"Nankou"},
{"cities":"Fontana"},
{"cities":"Golden"},
{"cities":"Gresik"},
{"cities":"La Molina"},
{"cities":"Mala Danylivka"},
{"cities":"Changshan"},
{"cities":"Purong"},
{"cities":"Longjumeau"},
{"cities":"Okhtyrka"},
{"cities":"Sumber"},
{"cities":"Pola"},
{"cities":"Tampa"},
{"cities":"Portela"},
{"cities":"Xinzheng"},
{"cities":"Palca"},
{"cities":"Peras Ruivas"},
{"cities":"Kālīganj"},
{"cities":"Nacka"},
{"cities":"Martaban"},
{"cities":"Changping"},
{"cities":"Loboniki"},
{"cities":"La Mesa"},
{"cities":"Cabaret"},
{"cities":"El Tambo"},
{"cities":"Neuilly-sur-Marne"},
{"cities":"Suwaduk"},
{"cities":"Custóias"},
{"cities":"Cikulahan"},
{"cities":"Dongjiao"},
{"cities":"Símantra"},
{"cities":"Berlin"},
{"cities":"Cañuelas"},
{"cities":"Şaḩneh"},
{"cities":"Liebu"},
{"cities":"Jianggang"},
{"cities":"Néa Smýrni"},
{"cities":"Narsingdi"},
{"cities":"Shentong"},
{"cities":"Gubat"},
{"cities":"Bucay"},
{"cities":"East Angus"},
{"cities":"Dambulla"},
{"cities":"Hōjō"},
{"cities":"Licheng"},
{"cities":"Ćićevac"},
{"cities":"Santo Domingo"},
{"cities":"Fais"},
{"cities":"Lamía"},
{"cities":"Americana"},
{"cities":"Waalwijk"},
{"cities":"Zhoutie"},
{"cities":"Shchastya"},
{"cities":"Castelsarrasin"},
{"cities":"Qiziltepa Shahri"},
{"cities":"Velikiye Luki"},
{"cities":"Shuitou"},
{"cities":"Cibungur"},
{"cities":"Rosh Ha‘Ayin"},
{"cities":"Nanbao"},
{"cities":"Chenji"},
{"cities":"Damaturu"},
{"cities":"Sannois"},
{"cities":"Maltahöhe"},
{"cities":"Al Manāqil"},
{"cities":"Caherconlish"},
{"cities":"Indaial"},
{"cities":"Krajan"},
{"cities":"São Roque"},
{"cities":"Nanhu"},
{"cities":"Prawdzinski"},
{"cities":"Notodden"},
{"cities":"Yaodian"},
{"cities":"Syzran’"},
{"cities":"Châteauroux"},
{"cities":"Khairiahmandah"},
{"cities":"Spodnja Hajdina"},
{"cities":"Misungwi"},
{"cities":"Roma"},
{"cities":"Marcabamba"},
{"cities":"Fier-Çifçi"},
{"cities":"Khu Khan"},
{"cities":"Sirte"},
{"cities":"Vernon"},
{"cities":"Changzhi"},
{"cities":"Nakano"},
{"cities":"Rio das Ostras"},
{"cities":"Voiron"},
{"cities":"Starominskaya"},
{"cities":"Borkowice"},
{"cities":"Gap"},
{"cities":"Punsu"},
{"cities":"Kertosari"},
{"cities":"Muqi"},
{"cities":"Nanggorak"},
{"cities":"Tiout"},
{"cities":"Wilmington"},
{"cities":"Kogota"},
{"cities":"Eido"},
{"cities":"Sępólno Krajeńskie"},
{"cities":"Pamyat’ Parizhskoy Kommuny"},
{"cities":"Butajīra"},
{"cities":"Kumamoto"},
{"cities":"Paris 09"},
{"cities":"Halimpu"},
{"cities":"Ílion"},
{"cities":"Sarmīn"},
{"cities":"Dazhangzhuang"},
{"cities":"Hongping"},
{"cities":"Sok Kwu Wan"},
{"cities":"Charleston"},
{"cities":"Achada"},
{"cities":"Villa Atamisqui"},
{"cities":"Orhei"},
{"cities":"Maiwang"},
{"cities":"Daduchuan"},
{"cities":"Botou"},
{"cities":"Zielona Góra"},
{"cities":"Wanshi"},
{"cities":"Guadalupe"},
{"cities":"Suḩayl Shibām"},
{"cities":"Leganes"},
{"cities":"Renyi"},
{"cities":"Uliastay"},
{"cities":"Lyon"},
{"cities":"Jiangna"},
{"cities":"Phu Sang"},
{"cities":"Pilar"},
{"cities":"Heping"},
{"cities":"Kanthararom"},
{"cities":"Guataquí"},
{"cities":"Kinshasa"},
{"cities":"Doroslovo"},
{"cities":"Netrakona"},
{"cities":"Aparecida"},
{"cities":"Nakhon Luang"},
{"cities":"Fontvieille"},
{"cities":"Ichnya"},
{"cities":"Kidričevo"},
{"cities":"Lenger"},
{"cities":"Petersfield"},
{"cities":"Kovylkino"},
{"cities":"Princeton"},
{"cities":"Pensacola"},
{"cities":"Sława"},
{"cities":"Bektemir"},
{"cities":"Vellinge"},
{"cities":"Jingtou"},
{"cities":"Horka nad Moravou"},
{"cities":"Trélissac"},
{"cities":"Pulau Pinang"},
{"cities":"Los Mangos"},
{"cities":"Casais Brancos"},
{"cities":"Hengxi"},
{"cities":"San Juan"},
{"cities":"Dongqianhu"},
{"cities":"Phoenix"},
{"cities":"Nefta"},
{"cities":"Masu"},
{"cities":"Qobu"},
{"cities":"Lengji"},
{"cities":"Delft"},
{"cities":"Bayan Qagan"},
{"cities":"Tungoo"},
{"cities":"Sezimovo Ústí"},
{"cities":"Daitou"},
{"cities":"Qianzhou"},
{"cities":"Gangnan"},
{"cities":"Erie"},
{"cities":"Mananjary"},
{"cities":"Rantaupanjang"},
{"cities":"Cacheu"},
{"cities":"Tabouda"},
{"cities":"Varser"},
{"cities":"Wudangshan"},
{"cities":"Gnieżdżewo"},
{"cities":"Sajan"}]

// Creates array out of cities data bank
download = arr => {
  arr.forEach(val => {
    cities.push(val.cities);
  });
}
download(data);
